badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  co2-emissions:
    envs:
      host:
        args: []
    path: pipelines/co2-emissions
    stages:
    - setup
    - run
    - validate
  data-science-no-stages:
    envs:
    - host
    envs:
      host:
        args: []
    path: pipelines/data-science-no-stages
    stages: []
  docker-data-science:
    envs:
    - host
    envs:
      host:
        args: []
    path: pipelines/docker-data-science
    stages:
    - build-docker-image
    - generate-learning-curves
    - generate-figures
    - validate
  sea-surface-mapping:
    envs:
    - host
    envs:
      host:
        args: []
    path: pipelines/sea-surface-mapping
    stages:
    - setup.sh
    - run.sh
search_sources:
- popperized
version: 1
