metadata: {}
pipelines:
  pipelines/co2-emissions:
    envs:
    - host
    path: pipelines/co2-emissions
    stages:
    - setup
    - run
    - validate
  sea-surface-mapping:
    envs:
    - host
    path: pipelines/sea-surface-mapping
    stages:
    - setup
    - get-data
    - transform-and-generate-map
